version: "3.3"

services:
  database:
    image: postgres
    container_name: database_ufuteria
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ufuteria
      - POSTGRES_PASSWORD=seminasnaotemmar
      - POSTGRES_DB=ufuteria
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ufuteria
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local